/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkstreamsRouteImport } from './routes/workstreams'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MitigationRouteImport } from './routes/mitigation'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const WorkstreamsRoute = WorkstreamsRouteImport.update({
  id: '/workstreams',
  path: '/workstreams',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MitigationRoute = MitigationRouteImport.update({
  id: '/mitigation',
  path: '/mitigation',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/engine': typeof EngineRoute
  '/intake': typeof IntakeRoute
  '/mitigation': typeof MitigationRoute
  '/register': typeof RegisterRoute
  '/workstreams': typeof WorkstreamsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/engine': typeof EngineRoute
  '/intake': typeof IntakeRoute
  '/mitigation': typeof MitigationRoute
  '/register': typeof RegisterRoute
  '/workstreams': typeof WorkstreamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/engine': typeof EngineRoute
  '/intake': typeof IntakeRoute
  '/mitigation': typeof MitigationRoute
  '/register': typeof RegisterRoute
  '/workstreams': typeof WorkstreamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/engine'
    | '/intake'
    | '/mitigation'
    | '/register'
    | '/workstreams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/engine'
    | '/intake'
    | '/mitigation'
    | '/register'
    | '/workstreams'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/engine'
    | '/intake'
    | '/mitigation'
    | '/register'
    | '/workstreams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EngineRoute: typeof EngineRoute
  IntakeRoute: typeof IntakeRoute
  MitigationRoute: typeof MitigationRoute
  RegisterRoute: typeof RegisterRoute
  WorkstreamsRoute: typeof WorkstreamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workstreams': {
      id: '/workstreams'
      path: '/workstreams'
      fullPath: '/workstreams'
      preLoaderRoute: typeof WorkstreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitigation': {
      id: '/mitigation'
      path: '/mitigation'
      fullPath: '/mitigation'
      preLoaderRoute: typeof MitigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EngineRoute: EngineRoute,
  IntakeRoute: IntakeRoute,
  MitigationRoute: MitigationRoute,
  RegisterRoute: RegisterRoute,
  WorkstreamsRoute: WorkstreamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
